//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektSem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wizyta
    {
        public int Id { get; set; }
        public int DoktorID { get; set; }
        public Nullable<int> PacjentID { get; set; }
        public System.DateTime Data_Wizyty { get; set; }
        public string Gabinet { get; set; }
        public string Pietro { get; set; }
    }
}
